name: Build Package (rootless)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install dpkg ldid xz

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
          echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV

      - name: Download iOS 16.5 SDK
        run: |
          mkdir -p $GITHUB_WORKSPACE/theos/sdks
          curl -L --fail -o /tmp/iPhoneOS16.5.sdk.tar.xz https://raw.githubusercontent.com/theos/sdks/master/iPhoneOS16.5.sdk.tar.xz
          file /tmp/iPhoneOS16.5.sdk.tar.xz
          ls -lh /tmp/iPhoneOS16.5.sdk.tar.xz
          tar -xf /tmp/iPhoneOS16.5.sdk.tar.xz -C $GITHUB_WORKSPACE/theos/sdks
          ls $GITHUB_WORKSPACE/theos/sdks/iPhoneOS16.5.sdk

      - name: Build tweak
        run: |
          make package FINALPACKAGE=1

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: skipDeviceFamilyCheck-rootless
          path: packages/*.deb
      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: skipDeviceFamilyCheck-rootless
          path: packages/*.deb
